
// configuration file for

//   ╔═════╦═════╗   ╔───╦═══════╗   ╔═══════╗   ╔═══════╗   ╔═══════╗   ╔═══════╗   ╔───╦════════───╗       ╔───════╦════───╦════╗    ╔───╦═══════╗   ╔════════───╦════════── MICROBRIGHTNESS
//   ║     ║     ║   ║   ║       ║   ║       ║   ║       ║   ║       ║   ║       ║   ║   ║           ║       ║       ║       ║    ║    ║   ║       │   ║           ║
//   ║     ║     ║   ║   ║       │   ║       ║   ║       ║   ║     ╔═╝   ║       ║   ║   ║           ║       ║       ║       ║    ║    ║   ║       │   ║           ║
//   ║     ║     ║   ║   ║       │   ╠═══╦═══╝   ║       ║   ╠═════╣     ╠═══╦═══╝   ║   ╠─────══╗   ╠═══════╣       ║       ║    ║    ║   ╠═══════╣   ╚═══════╗   ╚═══════╗
//   ║     ║     ║   ║   ║       │   ║   ║       ║       ║   ║     ╚═╗   ║   ║       ║   ║       ║   ║       ║       ║       ║    ║    ║   ║       │           ║           ║
//   ║     ║     ║   ║   ║       ║   ║   ║       ║       ║   ║       ║   ║   ║       ║   ║       ║   ║       ║       ║       ║    ║    ║   ║       │           ║           ║
// ──╩─────╩─────╩───╝   ╚═══════╩───╝   ╚════───╩═══════╩───╩═══════╩───╝   ╚════───╝   ╚═══════╝   ╚───────╩───────╩───────╝    ╚════╝   ╚═══════╩───════════╩───════════╝

use-messenger true;

set which-monitor-updates pointer;

// b-keycode none | shift | caps | control | mod-1 | mod-2 | mod-3 | mod-4 | mod-5 | any xyz press | release command parameter1 parameter2 parameter3 parameter4 parameter5
grab-keycode                                                         mod-4                72 press           increase-brightness 5;
grab-keycode                                                         mod-4                71 press           decrease-brightness 5;

